#
# Reference
# https://bukkit.gamepedia.com/Plugin_YAML
#
name: QuarryCraft2
main: com.randomlunacy.quarrycraft2.QuarryCraft2
version: 0.0.1
api-version: 1.18
website: https://www.randomlunacy.com/
depend: []
softdepend: []

commands:
  reload:
    aliases: [ 'qc2reload' ]
    description: Reload the configuration
    permission-message: Permission quarrycraft2.reload is required to use this command
    usage: /<command> to reload the QuarryCraft2 configuration.
  guide:
    aliases: [ 'qc2guide' ]
    description: Gives player a guide to QuarryCraft2
    permission-message: Permission quarrycraft2.guide is required to use this command
    usage: /<command> to receive a QuarryCraft2 guide

permissions:
  quarrycraft2.*:
    description: Gives access to all QuarryCraft2 commands
    children:
      quarrycraft2.reload: true
  quarrycraft2.reload:
    description: Gives access to hte qc2reload command
    default: op
  quarrycraft2.guide:
    description: Gives access to the qc2guide command
    default: true
  quarrycraft2.build:
    description: Gives permission to build quarries
    default: op
  quarrycraft2.use:
    description: Gives permission to interact with quarries
    default: true
  quarrycraft2.useall:
    description: Give permission to interact with all quarries
    default: op
